/// <reference types="jquery" />
/// <reference types="tooltipster" />
import { ActorSheetPF2e } from "../sheet/base";
import { HazardPF2e } from ".";
import { ActorSheetDataPF2e } from "@actor/sheet/data-types";
/** In development version of the hazard sheet. */
export declare class HazardSheetGreenPF2e extends ActorSheetPF2e<HazardPF2e> {
    static get defaultOptions(): ActorSheetOptions;
    get template(): string;
    get editing(): boolean;
    getData(): Promise<{
        editing: boolean;
        flags: any;
        hazardTraits: {
            aquatic: string;
            alchemical: string;
            auditory: string;
            clockwork: string;
            consumable: string;
            curse: string;
            environmental: string;
            fungus: string;
            haunt: string;
            inhaled: string;
            kaiju: string;
            magical: string;
            mechanical: string;
            steam: string;
            summoned: string;
            technological: string;
            teleportation: string;
            trap: string;
            virulent: string;
            arcane: string;
            divine: string;
            occult: string;
            primal: string;
            abjuration: string;
            conjuration: string;
            divination: string;
            enchantment: string;
            evocation: string;
            illusion: string;
            necromancy: string;
            transmutation: string;
            light: string;
            mental: string;
            nonlethal: string;
            plant: string;
            radiation: string;
            acid: string;
            cold: string;
            electricity: string;
            fire: string;
            force: string;
            negative: string;
            positive: string;
            sonic: string;
            air: string;
            earth: string;
            water: string;
            chaotic: string;
            evil: string;
            good: string;
            lawful: string;
        };
        actorTraits: string[];
        rarity: {
            common: string;
            uncommon: string;
            rare: string;
            unique: string;
        };
        rarityLabel: string;
        stealthDC: number;
        hasStealthDescription: string | boolean;
        hasImmunities: boolean;
        hasResistances: boolean;
        hasWeaknesses: boolean;
        hasDescription: string | boolean;
        hasDisable: string | boolean;
        hasRoutineDetails: string | boolean;
        hasResetDetails: string | boolean;
        hasHPDetails: string | boolean;
        hasWillSave: boolean;
        brokenThreshold: number;
        traits: import("../../sheet/helpers").SheetOptions;
        isTargetFlatFooted: boolean;
        user: {
            isGM: boolean;
        };
        hasRealContainers?: boolean | undefined;
        totalCoinage: import("@actor/sheet/data-types").CoinageSummary;
        totalCoinageGold: string;
        totalWealth: import("../../item/treasure/helpers").Coins;
        totalWealthGold: string;
        immunities: import("../../sheet/helpers").SheetOptions;
        actor: any;
        data: any;
        items: any;
        cssClass: "editable" | "locked";
        effects: RawObject<foundry.data.ActiveEffectData<foundry.documents.BaseActiveEffect>>[];
        limited: boolean;
        options: ActorSheetOptions;
        editable: boolean;
        document: HazardPF2e;
        owner: boolean;
        title: string;
    }>;
    prepareItems(sheetData: ActorSheetDataPF2e<HazardPF2e>): void;
    activateListeners($html: JQuery): void;
}
